version: '3.7'
services:
  web:
    ports:
      - "69:69"
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - LANDLORD_ADDRESS
      - RPC_URL
    container_name: solution-web
