version: "3.9"

services:
    web:
        build:
            context: backend
            dockerfile: Dockerfile
        command: python manage.py runserver solution-web:80
        ports:
            - "80:80"
        environment:
            - LANDLORD_ADDRESS
            - RPC_URL
        container_name: solution-web
