# Generated by Django 3.2.11 on 2022-03-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmogusApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
    ]
