# Generated by Django 3.2.11 on 2022-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmogusApp', '0002_alter_authentication_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='name',
        ),
        migrations.AddField(
            model_name='authentication',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
        ),
    ]
