# Generated by Django 3.2.11 on 2022-03-17 20:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('AmogusApp', '0003_auto_20220315_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('internalName', models.TextField(default='', verbose_name='internalName')),
                ('area', models.FloatField(verbose_name='area')),
                ('location', models.TextField(default='', verbose_name='location')),
            ],
        ),
    ]
