# Generated by Django 3.2.11 on 2022-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmogusApp', '0005_auto_20220318_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='contractAddress',
            field=models.TextField(blank=True, null=True, verbose_name='contractAddress'),
        ),
        migrations.AlterField(
            model_name='room',
            name='publicName',
            field=models.TextField(blank=True, null=True, verbose_name='publicName'),
        ),
    ]
